#!/bin/bash

trap times EXIT

source SET_VARS

CLS="de.uni_mannheim.informatik.dws.tnt.match.cli.EvaluateEntityStitchedUnionTables"
LOG="datasets/evaluation_results_containment.tsv"

host="$1"

echo $(date)": evaluating $host"

TBL="$host/normalised_S_fd_relations"
EVAL="$host/evaluation/normalised_fd_relations"

$J8 $VMARGS -cp $JAR $CLS -tables $TBL -reference $EVAL -containment -globalLog $LOG -labelsMatch -filenamesMatch > $host/evaluate_containment_S.log 2>&1

echo $(date)": $host done."
