#!/bin/bash

trap times EXIT

source SET_VARS

CLS="de.uni_mannheim.informatik.dws.tnt.match.cli.EvaluateEntityStitchedUnionTables"
LOG="datasets/evaluation_results_containment.tsv"

#rm $LOG
#rm $LOG"_details.tsv"

MATCHER="Trivial"

for host in datasets/*/
do
	EVAL="$host/evaluation/normalised_fd_relations"

	TBL="$host/normalised_S_fd_relations"
	echo $(date)": evaluating $host - $TBL"
	$J8 $VMARGS -cp $JAR $CLS -tables $TBL -reference $EVAL -globalLog $LOG -containment -labelsMatch -filenamesMatch > $host/evaluate_containment_S.log 2>&1
	
	TBL="$host/normalised_S_noContextColumns_fd_relations"
	echo $(date)": evaluating $host - $TBL"
	$J8 $VMARGS -cp $JAR $CLS -tables $TBL -reference $EVAL -globalLog $LOG -containment -labelsMatch -filenamesMatch > $host/evaluate_containment_S_noContextColumns.log 2>&1
	
	TBL="$host/normalised_B_fd_relations"
	echo $(date)": evaluating $host - $TBL"
	$J8 $VMARGS -cp $JAR $CLS -tables $TBL -reference $EVAL -globalLog $LOG -containment -labelsMatch -filenamesMatch > $host/evaluate_containment_B.log 2>&1

	TBL="$host/normalised_M_fd_relations"
	echo $(date)": evaluating $host - $TBL"
	$J8 $VMARGS -cp $JAR $CLS -tables $TBL -reference $EVAL -globalLog $LOG -containment -labelsMatch -filenamesMatch > $host/evaluate_containment_M.log 2>&1
	
	TBL="$host/normalised_M_norm_fd_relations"
	echo $(date)": evaluating $host - $TBL"
	$J8 $VMARGS -cp $JAR $CLS -tables $TBL -reference $EVAL -globalLog $LOG -containment -labelsMatch -filenamesMatch > $host/evaluate_containment_M_normalised.log 2>&1

	echo $(date)": $host done."

done
